"""Get app settings from the environment."""

from __future__ import absolute_import, unicode_literals

from django.conf import settings


ENV_TOKENS = getattr(settings, "ENV_TOKENS", {}).get('APPSEMBLER_FEATURES', {})

USE_OPEN_ENDED_CERTS_DEFAULTS = ENV_TOKENS.get("USE_OPEN_ENDED_CERTS_DEFAULTS", False)
ACTIVATE_DEFAULT_CERTS = ENV_TOKENS.get("ACTIVATE_DEFAULT_CERTS", True)
ALWAYS_ENABLE_SELF_GENERATED_CERTS = ENV_TOKENS.get("ALWAYS_ENABLE_SELF_GENERATED_CERTS", False)
DISABLE_SELF_GENERATED_CERTS_FOR_SELF_PACED = ENV_TOKENS.get("DISABLE_SELF_GENERATED_CERTS_FOR_SELF_PACED", False)
CERTS_HTML_VIEW_CONFIGURATION = ENV_TOKENS.get("CERTS_HTML_VIEW_CONFIGURATION", None)
LINKEDIN_ADDTOPROFILE_COMPANY_ID = ENV_TOKENS.get("LINKEDIN_ADDTOPROFILE_COMPANY_ID", None)
LINKEDIN_ADDTOPROFILE_LICENSE_ID = ENV_TOKENS.get("LINKEDIN_ADDTOPROFILE_LICENSE_ID", None)
DEFAULT_CERT_SIGNATORIES = ENV_TOKENS.get("DEFAULT_CERT_SIGNATORIES", None)
